---
- name: Setup apache and mariadb-client
  hosts: tag_Name_Dev_ec2
  gather_facts: false
  become: yes
  tasks:

    - name: apt-get upgrade
      apt:
        name: "*"
        state: latest
        update_cache: yes

    - name: Install Apache2 on  ubuntu
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      loop:
        - apache2
        - mariadb-client
    - name: start and enable apache2
      service:
        name: apache2
        state: started
        enabled: yes
    - name: add Index.html
      copy:
        dest: /var/www/html/index.html
        content: |
          <h1> Test is succesed </h1>
      

